export const GET_ORDER_REQUEST: 'GET_ORDER_REQUEST' = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS' = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAILED: 'GET_ORDER_FAILED' = 'GET_ORDER_FAILED';
export const CLOSE_ORDER_MODAL: 'CLOSE_ORDER_MODAL' = 'CLOSE_ORDER_MODAL';

export const GET_ORDERS_REQUEST: 'GET_ORDERS_REQUEST' = 'GET_ORDERS_REQUEST';
export const GET_ORDERS_SUCCESS: 'GET_ORDERS_SUCCESS' = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILED: 'GET_ORDERS_FAILED' = 'GET_ORDERS_FAILED';

export const GET_MY_ORDERS_REQUEST: 'GET_MY_ORDERS_REQUEST' = 'GET_MY_ORDERS_REQUEST';
export const GET_MY_ORDERS_SUCCESS: 'GET_MY_ORDERS_SUCCESS' = 'GET_MY_ORDERS_SUCCESS';
export const GET_MY_ORDERS_FAILED: 'GET_MY_ORDERS_FAILED' = 'GET_MY_ORDERS_FAILED';

export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_START: 'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_GET_MESSAGE: 'WS_GET_MESSAGE' = 'WS_GET_MESSAGE';

export const WS_CONNECTION_MY_CLOSED: 'WS_CONNECTION_MY_CLOSED' = 'WS_CONNECTION_MY_CLOSED';
export const WS_CONNECTION_MY_ERROR: 'WS_CONNECTION_MY_ERROR' = 'WS_CONNECTION_MY_ERROR';
export const WS_CONNECTION_MY_START: 'WS_CONNECTION_MY_START' = 'WS_CONNECTION_MY_START';
export const WS_CONNECTION_MY_SUCCESS: 'WS_CONNECTION_MY_SUCCESS' = 'WS_CONNECTION_MY_SUCCESS';
export const WS_GET_MY_MESSAGE: 'WS_GET_MY_MESSAGE' = 'WS_GET_MY_MESSAGE';
